### ISSUE TITLE
Dataset open problem

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [kleincup/DGMS#4]
Hello, sorry to bother you, How can I Open the. PT file for the dataset? For example, text_0.pt,

I can only see the shape of the .pt file

like below
Data(edge_attr=[38, 3], edge_index=[2, 38], x=[18, 300])

Thank you very much

**Comment by ryderling** [comment]
Thanks for your attention.  Data is one kind of data structure defined by PyTorch officially. See https://pytorch.org/docs/stable/data.html for details.

**Comment by skye95git** [comment]
> Hello, sorry to bother you, How can I Open the. PT file for the dataset? For example, text_0.pt,
> 
> I can only see the shape of the .pt file
> 
> like below Data(edge_attr=[38, 3], edge_index=[2, 38], x=[18, 300])
> 
> Thank you very much

Hi, how do you print the message `Data(edge_attr=[38, 3], edge_index=[2, 38], x=[18, 300])`? When I print it, there is an error `The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.`
